swagger: '2.0'
schemes:
- https
produces:
- application/json
paths:
  /autocomplete/{query}:
    get:
      x-google-backend:
        address: https://autocomplete-bw5n3iokeq-ew.a.run.app
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
        deadline: 15
      operationId: get_get_autocomplete
      parameters:
      - in: path
        name: query
        required: true
        type: string
      responses:
        '200':
          description: A successful response
info:
  title: autocomplete
  version: 1.0.0
